### ISSUE TITLE
Fix concurrent map-write race condition for nulldb

### ISSUE THREAD

**Issue by meganokeefe** [sigma-dev/sigma#207]
We've had a manager todo for concurrent map writes: https://github.com/sigma-dev/sigma/blob/master/manager/manager.go#L184 

Hit this error in travis, in the manager integration tests where the update-interval is `200ms`. 

Exact error is: 
`fatal error: concurrent map writes` error 

Trace:
```
goroutine 188 [running]:
runtime.throw(0xcea6a3, 0x15)
	/home/travis/.gimme/versions/go1.7.1.linux.amd64/src/runtime/panic.go:566 +0x95 fp=0xc42017cd60 sp=0xc42017cd40
runtime.mapassign1(0xbd1c40, 0xc4203606f0, 0xc42057af08, 0xc42017cf80)
	/home/travis/.gimme/versions/go1.7.1.linux.amd64/src/runtime/hashmap.go:553 +0x2e1 fp=0xc42017ce48 sp=0xc42017cd60
github.com/sigma-dev/sigma/task.(*DockerTasker).Run(0xc420320550, 0xc42057af00, 0xc42017d110, 0xc42017d110)
	/home/travis/gopath/src/github.com/sigma-dev/sigma/task/docker.go:184 +0x82c fp=0xc42017d0a0 sp=0xc42017ce48
github.com/sigma-dev/sigma/manager.(*manager).startOperation(0xc42032ed00, 0xc4205817d0, 0xc4204c0210, 0x2e, 0xcdd75c, 0x6, 0xcdfe09, 0x8, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/sigma-dev/sigma/manager/manager.go:388 +0xbd fp=0xc42017d140 sp=0xc42017d0a0
github.com/sigma-dev/sigma/manager.(*manager).updateOperations(0xc42032ed00, 0xc4205817d0, 0xc4204c0210, 0x2e, 0xcdd75c, 0x6, 0xcdfe09, 0x8, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/sigma-dev/sigma/manager/manager.go:362 +0x4b6 fp=0xc42017d3f8 sp=0xc42017d140
github.com/sigma-dev/sigma/manager.(*manager).updateService(0xc42032ed00, 0xc4203e18c0, 0x24)
	/home/travis/gopath/src/github.com/sigma-dev/sigma/manager/manager.go:253 +0x2a0 fp=0xc42017df60 sp=0xc42017d3f8
github.com/sigma-dev/sigma/manager.(*manager).Start.func1(0xc42032ed00, 0xc4203e18c0, 0x24)
	/home/travis/gopath/src/github.com/sigma-dev/sigma/manager/manager.go:178 +0x74 fp=0xc42017df88 sp=0xc42017df60
runtime.goexit()
	/home/travis/.gimme/versions/go1.7.1.linux.amd64/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42017df90 sp=0xc42017df88
created by github.com/sigma-dev/sigma/manager.(*manager).Start
	/home/travis/gopath/src/github.com/sigma-dev/sigma/manager/manager.go:184 +0x2d8
``` 

Relevant build: https://travis-ci.org/sigma-dev/sigma/builds/248494670?utm_source=github_status&utm_medium=notification

**Comment by meganokeefe** [comment]
Turned out this was a dockershipper problem, removing the map that caused this problem.
