### ISSUE TITLE
If fluentd connection fails, sigma panics

### ISSUE THREAD

**Issue by mikeynap** [sigma-dev/sigma#418]
```Failed to fire hook: fluent#send: can't send logs, client is reconnecting
INFO[2017-11-09T01:31:58-05:00] Started 'Deploy' Operation 63f7208d-b0d8-4ed8-862d-d80562590839  Service=8d0efe9c-78a1-4e09-a653-54a9665c1a1c
panic: fluent#reconnect: failed to reconnect!

goroutine 13464 [running]:
github.com/sigma-dev/sigma/vendor/github.com/fluent/fluent-logger-golang/fluent.(*Fluent).reconnect(0xc420378300)
	/Users/mnapolit/go/src/github.com/sigma-dev/sigma/vendor/github.com/fluent/fluent-logger-golang/fluent/fluent.go:290 +0xd9
created by github.com/sigma-dev/sigma/vendor/github.com/fluent/fluent-logger-golang/fluent.(*Fluent).send
	/Users/mnapolit/go/src/github.com/sigma-dev/sigma/vendor/github.com/fluent/fluent-logger-golang/fluent/fluent.go:304 +0x13c```

**Comment by meganokeefe** [comment]
How did you trigger this behavior @mikeynap ?
