### ISSUE TITLE
Manager panics when updating a serviceOperation

### ISSUE THREAD

**Issue by meganokeefe** [sigma-dev/sigma#57]
Getting an `interface-> time.Time` type assertion error that causes sigma to panic.

Running sigma with sudo. Added a service that uses the `ditto` plugin. My service: 
```
{
	"Name": "serviceditto",
	"Plugin": "ditto/v1", 
	"Site": "local", 
	"Input": [
		{
		"Name": "megan", 
		"Value": "blah"
		}
		]
}
```

On runtime:
```
➜  sigma git:(sites-manager) sudo ./bin/sigma --config ./config.yaml
INFO[2017-05-09T10:54:41-04:00]
  _________.__  ________            _____
 /   _____/|__|/  _____/  _____    /  _  \
 \_____  \ |  /   \  ___ /     \  /  /_\  \
 /        \|  \    \_\  \  Y Y  \/    |    \
/_______  /|__|\______  /__|_|  /\____|__  /
        \/            \/      \/         \/   file=sigma.go line=61
INFO[2017-05-09T10:55:00-04:00] Started Operation 1412a15a-6ec0-435d-9443-7ac018c4e051-operation (Deploy)  file=manager.go line=265
ERRO[2017-05-09T10:55:01-04:00] Could not operate service "serviceditto"      error="InsertServiceOperation error: key already exists" file=manager.go line=383
panic: interface conversion: interface is string, not time.Time

goroutine 68 [running]:
panic(0x524d20, 0xc420541140)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/sigma-dev/sigma/manager.(*manager).updateOperations(0xc42044c070)
	/Users/meokeefe/Documents/go/src/github.com/sigma-dev/sigma/manager/manager.go:230 +0x395
github.com/sigma-dev/sigma/manager.(*manager).Start(0xc42044c070, 0x60ef50, 0xc420441c20)
	/Users/meokeefe/Documents/go/src/github.com/sigma-dev/sigma/manager/manager.go:134 +0x174
github.com/sigma-dev/sigma/vendor/github.com/stephenrlouie/service.(*ServiceGroup).wrapSvc(0xc4202d9110, 0x843f00, 0xc42044c070, 0xc420441c20)
	/Users/meokeefe/Documents/go/src/github.com/sigma-dev/sigma/vendor/github.com/stephenrlouie/service/helpers.go:100 +0x8b
created by github.com/sigma-dev/sigma/vendor/github.com/stephenrlouie/service.(*ServiceGroup).Start
	/Users/meokeefe/Documents/go/src/github.com/sigma-dev/sigma/vendor/github.com/stephenrlouie/service/helpers.go:53 +0xe0
```

**Comment by adamschaub** [comment]
Is this on master or another branch?

**Comment by stephenrlouie** [comment]
##Replicate

1. `git checkout ex`
2. `make`
3. `./database/cbdeploy.sh`
4. `./bin/sigma --config config.yaml`
5. `./examples/hello-world/add-plugin.sh`
6. `./examples/hello-world/add-service.sh`
